<?php
require_once __DIR__ . '/mail_config.php';

function munch_base_url() {
    $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
    $path = rtrim(dirname($_SERVER['SCRIPT_NAME'] ?? '/munch/'), '/\\');
    return $scheme . '://' . $host . $path;
}

function munch_safe_filename($value) {
    $value = preg_replace('/[^A-Za-z0-9_\-\.]/', '_', (string)$value);
    return trim($value, '_') ?: 'email';
}

function munch_outbox_dir() {
    $dir = __DIR__ . '/emails_outbox';
    if (!is_dir($dir)) {
        mkdir($dir, 0775, true);
    }
    $attachmentDir = $dir . '/attachments';
    if (!is_dir($attachmentDir)) {
        mkdir($attachmentDir, 0775, true);
    }
    return $dir;
}

function munch_send_email($to, $subject, $htmlBody, $attachmentBytes = null, $attachmentName = null) {
    $to = trim((string)$to);
    $subject = trim((string)$subject);
    $outbox = munch_outbox_dir();
    $timestamp = date('Ymd_His');
    $safeSubject = munch_safe_filename(substr($subject, 0, 60));
    $baseName = $timestamp . '_' . $safeSubject;

    $attachmentPath = '';
    if ($attachmentBytes !== null && $attachmentName) {
        $attachmentPath = $outbox . '/attachments/' . $baseName . '_' . munch_safe_filename($attachmentName);
        file_put_contents($attachmentPath, $attachmentBytes);
    }

    $debugHtml = "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>" . htmlspecialchars($subject) . "</title>" .
        "<style>body{font-family:Arial,sans-serif;background:#f6f7f4;padding:24px;color:#1f2933}.mail{max-width:760px;margin:auto;background:#fff;border-radius:18px;padding:26px;box-shadow:0 14px 40px rgba(0,0,0,.08)}.meta{font-size:13px;color:#64748b;border-bottom:1px solid #e5e7eb;padding-bottom:14px;margin-bottom:18px}.attach{margin-top:18px;padding:12px;background:#f0fdf4;border-radius:12px}</style></head><body><div class='mail'>" .
        "<div class='meta'><strong>LOCALHOST EMAIL OUTBOX</strong><br>To: " . htmlspecialchars($to) . "<br>Subject: " . htmlspecialchars($subject) . "<br>Created: " . date('Y-m-d H:i:s') . "</div>" .
        $htmlBody .
        ($attachmentPath ? "<div class='attach'><strong>Attachment saved:</strong> " . htmlspecialchars(basename($attachmentPath)) . "</div>" : "") .
        "</div></body></html>";

    $outboxPath = $outbox . '/' . $baseName . '.html';
    file_put_contents($outboxPath, $debugHtml);

    $sentByMail = false;
    if (defined('MUNCH_USE_PHP_MAIL') && MUNCH_USE_PHP_MAIL && filter_var($to, FILTER_VALIDATE_EMAIL)) {
        $headers = "MIME-Version: 1.0\r\n";
        $headers .= "Content-type:text/html;charset=UTF-8\r\n";
        $headers .= "From: " . MUNCH_FROM_NAME . " <" . MUNCH_FROM_EMAIL . ">\r\n";
        $sentByMail = @mail($to, $subject, $htmlBody, $headers);
    }

    return [
        'success' => true,
        'sent_by_php_mail' => $sentByMail,
        'outbox_file' => $outboxPath,
        'attachment_file' => $attachmentPath
    ];
}

function munch_email_template($title, $message, $buttonText = '', $buttonUrl = '') {
    $button = '';
    if ($buttonText && $buttonUrl) {
        $button = "<p style='margin:24px 0'><a href='" . htmlspecialchars($buttonUrl) . "' style='background:#0f766e;color:#fff;text-decoration:none;padding:12px 18px;border-radius:999px;font-weight:700;display:inline-block'>" . htmlspecialchars($buttonText) . "</a></p>";
    }

    return "<div style='font-family:Arial,sans-serif;max-width:680px;margin:auto;background:#ffffff;border-radius:18px;padding:24px;border:1px solid #e5e7eb'>" .
        "<h1 style='margin:0 0 10px;color:#0f766e'>" . htmlspecialchars($title) . "</h1>" .
        "<div style='font-size:15px;line-height:1.7;color:#334155'>" . $message . "</div>" .
        $button .
        "<p style='margin-top:24px;font-size:13px;color:#64748b'>This email is generated by the Munch prototype system.</p>" .
        "</div>";
}
?>
